// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncufgpkvicwbbhrzwkro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWZncGt2aWN3YmJocnp3a3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjQ0NjksImV4cCI6MjA3MDM0MDQ2OX0.OsAmjbmQFfkYAISLuikXbmuWXfB4px9dCI0ykRM87rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});